#!/bin/sh
LOG="/tmp/apply"
date >> ${LOG}
echo "$*" >> ${LOG}

cp $* common.yaml
/usr/local/bin/puppet apply ./init.pp --show_diff --hiera_config=/usr/home/oleg/cbsd-mq-api/hiera.yaml

echo "Done"
exit 0
